# Sample related
in_dir: "/mnt/AchTeraD/data/210406_NS500140_0371_AHTL27AFX2/fastq/"
out_dir: "/mnt/AchTeraD/data/BICRO280/"
sample: "MS169_S1"
paired: True
lanesplit: True

# Semi-static variables
bc: "/mnt/AchTeraD/data/210406_NS500140_0371_AHTL27AFX2/barcodes.txt"
cutsites: "/mnt/AchTeraD/Documents/Projects/COVseq/cutsite-distribution/sars-cov-2_NlaIII-MseI-cutsites.bed"
bed: "/mnt/AchTeraD/Documents/Projects/COVseq/cov2-primers/sars-cov-2_primer-pool.bed"
readlength: 130
# Reference
ref: "/mnt/AchTeraD/Documents/references/sars-cov-2/NC_045512.2.fasta.gz"
mm: 1
# Tools
demux: "python3 /mnt/AchTeraD/Documents/Projects/scCUTseq/Scripts/preprocessing-pipeline/demultiplex/demultiplex_withcython.py"
getReads: "/mnt/AchTeraD/Documents/Projects/scCUTseq/Scripts/preprocessing-pipeline/Extract_readnames_nearCutsites.R"

threads: 32